name: dart_otp
description: dart_otp is a dart package to generate and verify one-time passwords.
version: 1.3.0

publish_to: 'none'
homepage: https://github.com/longht021189/dart_otp

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  crypto: ^3.0.2
  base32: ^2.1.3

dev_dependencies:
  test: ^1.21.3